/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#241a00",
        "tertiary-fixed-dim": "#e7c365",
        "on-primary-fixed": "#22005d",
        "on-secondary-fixed-variant": "#4b4263",
        "primary": "#4f378a",
        "outline": "#7a7582",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e6e0e9",
        "surface-container-high": "#ece6ee",
        "inverse-primary": "#cfbcff",
        "outline-variant": "#cbc4d2",
        "secondary-fixed-dim": "#cdc0e9",
        "inverse-surface": "#322f35",
        "secondary-container": "#e1d4fd",
        "on-secondary-container": "#645a7d",
        "on-tertiary-container": "#503d00",
        "surface-container": "#f2ecf4",
        "surface-dim": "#ded8e0",
        "on-primary": "#ffffff",
        "secondary-fixed": "#e9ddff",
        "secondary": "#63597c",
        "on-secondary-fixed": "#1f1635",
        "primary-container": "#6750a4",
        "tertiary-container": "#c9a74d",
        "tertiary": "#765b00",
        "surface-container-low": "#f8f2fa",
        "on-tertiary": "#ffffff",
        "surface": "#fdf7ff",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#594400",
        "on-surface-variant": "#494551",
        "surface-bright": "#fdf7ff",
        "background": "#fdf7ff",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#6750a4",
        "primary-fixed": "#e9ddff",
        "on-primary-fixed-variant": "#4f378a",
        "on-surface": "#1d1b20",
        "primary-fixed-dim": "#cfbcff",
        "on-primary-container": "#e0d2ff",
        "on-error": "#ffffff",
        "error": "#ba1a1a",
        "surface-variant": "#e6e0e9",
        "inverse-on-surface": "#f5eff7",
        "tertiary-fixed": "#ffdf93",
        "on-background": "#1d1b20",
        "action-orange": "#FF6B00",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "touch_target": "44px",
        "xs": "4px",
        "xl": "32px",
        "lg": "24px",
        "md": "16px",
        "unit": "4px",
        "sm": "8px"
      },
      fontFamily: {
        "sans": ["Inter", "sans-serif"],
        "headline-md": ["Inter"],
        "headline-lg": ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "display-lg": ["Inter"],
        "label-md": ["Inter"],
        "label-sm": ["Inter"],
        "price-display": ["Inter"]
      },
      fontSize: {
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-md": ["14px", { "lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "label-sm": ["12px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "price-display": ["28px", { "lineHeight": "1", "letterSpacing": "-0.01em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
